spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos
    username: postgres
    password: 12345
  jpa:
      hibernate:
      ddl-auto: update # Ou "create", "validate", dependendo do comportamento desejado

